export const LOGO_URL =
  "https://media.istockphoto.com/id/185284489/photo/orange.jpg?s=612x612&w=0&k=20&c=m4EXknC74i2aYWCbjxbzZ6EtRaJkdSJNtekh4m1PspE=";
export const CART_LOGO_URL =
  "https://cdn.pixabay.com/photo/2014/04/02/10/53/shopping-cart-304843_640.png";

export const DATA_ARRAY = [
  {
    name: "Maaldaar Fruits",
    img: "https://content.jdmagicbox.com/comp/def_content_category/fruit-retailers/0d5fc373c6-fruit-retailers-1-oeewf.jpg",
    id: 2,
    rating: 4.4,
    delivery: 43,
    price: 80,
  },
  {
    name: "Chitle Fruits",
    img: "https://kj1bcdn.b-cdn.net/media/78570/fruit-bussiness.jpg",
    id: 3,
    rating: 4.1,
    delivery: 32,
    price: 65,
  },
  {
    name: "Atithi Shopee",
    img: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRGV2IRDGgR0eTLfxCiFLe51VDX1HFw6PUzrw&s",
    id: 4,
    rating: 4.7,
    delivery: 36,
    price: 120,
  },
  {
    name: "Lizzat Fruits",
    img: "https://i.ytimg.com/vi/Y1aVOCgVjhc/maxresdefault.jpg?sqp=-oaymwEmCIAKENAF8quKqQMa8AEB-AH-CYAC0AWKAgwIABABGHIgWygtMA8=&rs=AOn4CLASGk6xuSwubigEfcpa_OADeUM8rA",
    id: 6,
    rating: 4.4,
    delivery: 43,
    price: 80,
  },
  {
    name: "Soni Fruits",
    img: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSlTxho4ctAuGF119v5lR4Qe1Xfj7l13gg7Cw&s",
    id: 7,
    rating: 4.1,
    delivery: 32,
    price: 65,
  },
  {
    name: "Arohi",
    img: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSpEukxvZzHmnQf4iEnp2bS6W5Ym8CjoaOh1w&s",
    id: 8,
    rating: 4.7,
    delivery: 36,
    price: 120,
  },
  {
    name: "Atithi Shopee",
    img: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRGV2IRDGgR0eTLfxCiFLe51VDX1HFw6PUzrw&s",
    id: 9,
    rating: 4.7,
    delivery: 36,
    price: 120,
  },
  {
    name: "Lizzat Fruits",
    img: "https://i.ytimg.com/vi/Y1aVOCgVjhc/maxresdefault.jpg?sqp=-oaymwEmCIAKENAF8quKqQMa8AEB-AH-CYAC0AWKAgwIABABGHIgWygtMA8=&rs=AOn4CLASGk6xuSwubigEfcpa_OADeUM8rA",
    id: 10,
    rating: 4.4,
    delivery: 43,
    price: 80,
  },
  {
    name: "Soni Fruits",
    img: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSlTxho4ctAuGF119v5lR4Qe1Xfj7l13gg7Cw&s",
    id: 11,
    rating: 4.1,
    delivery: 32,
    price: 65,
  },
  {
    name: "Maaldaar Fruits",
    img: "https://content.jdmagicbox.com/comp/def_content_category/fruit-retailers/0d5fc373c6-fruit-retailers-1-oeewf.jpg",
    id: 12,
    rating: 4.4,
    delivery: 43,
    price: 80,
  },
  {
    name: "Chitle Fruits",
    img: "https://kj1bcdn.b-cdn.net/media/78570/fruit-bussiness.jpg",
    id: 13,
    rating: 4.1,
    delivery: 32,
    price: 65,
  },
  {
    name: "Atithi Shopee",
    img: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRGV2IRDGgR0eTLfxCiFLe51VDX1HFw6PUzrw&s",
    id: 14,
    rating: 4.7,
    delivery: 36,
    price: 120,
  },
  {
    name: "Lizzat Fruits",
    img: "https://i.ytimg.com/vi/Y1aVOCgVjhc/maxresdefault.jpg?sqp=-oaymwEmCIAKENAF8quKqQMa8AEB-AH-CYAC0AWKAgwIABABGHIgWygtMA8=&rs=AOn4CLASGk6xuSwubigEfcpa_OADeUM8rA",
    id: 16,
    rating: 4.4,
    delivery: 43,
    price: 80,
  },
  {
    name: "Soni Fruits",
    img: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSlTxho4ctAuGF119v5lR4Qe1Xfj7l13gg7Cw&s",
    id: 17,
    rating: 4.1,
    delivery: 32,
    price: 65,
  },
  {
    name: "Arohi",
    img: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSpEukxvZzHmnQf4iEnp2bS6W5Ym8CjoaOh1w&s",
    id: 18,
    rating: 4.7,
    delivery: 36,
    price: 120,
  },
  {
    name: "Atithi Shopee",
    img: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRGV2IRDGgR0eTLfxCiFLe51VDX1HFw6PUzrw&s",
    id: 24,
    rating: 4.7,
    delivery: 36,
    price: 120,
  },
  {
    name: "Lizzat Fruits",
    img: "https://i.ytimg.com/vi/Y1aVOCgVjhc/maxresdefault.jpg?sqp=-oaymwEmCIAKENAF8quKqQMa8AEB-AH-CYAC0AWKAgwIABABGHIgWygtMA8=&rs=AOn4CLASGk6xuSwubigEfcpa_OADeUM8rA",
    id: 26,
    rating: 4.4,
    delivery: 43,
    price: 80,
  },
  {
    name: "Maaldaar Fruits",
    img: "https://content.jdmagicbox.com/comp/def_content_category/fruit-retailers/0d5fc373c6-fruit-retailers-1-oeewf.jpg",
    id: 32,
    rating: 4.4,
    delivery: 43,
    price: 80,
  },
  {
    name: "Chitle Fruits",
    img: "https://kj1bcdn.b-cdn.net/media/78570/fruit-bussiness.jpg",
    id: 33,
    rating: 4.1,
    delivery: 32,
    price: 65,
  },
  {
    name: "Atithi Shopee",
    img: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRGV2IRDGgR0eTLfxCiFLe51VDX1HFw6PUzrw&s",
    id: 34,
    rating: 4.7,
    delivery: 36,
    price: 120,
  },
  {
    name: "Lizzat Fruits",
    img: "https://i.ytimg.com/vi/Y1aVOCgVjhc/maxresdefault.jpg?sqp=-oaymwEmCIAKENAF8quKqQMa8AEB-AH-CYAC0AWKAgwIABABGHIgWygtMA8=&rs=AOn4CLASGk6xuSwubigEfcpa_OADeUM8rA",
    id: 36,
    rating: 4.4,
    delivery: 43,
    price: 80,
  },
  {
    name: "Soni Fruits",
    img: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSlTxho4ctAuGF119v5lR4Qe1Xfj7l13gg7Cw&s",
    id: 37,
    rating: 4.1,
    delivery: 32,
    price: 65,
  },
  {
    name: "Arohi",
    img: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSpEukxvZzHmnQf4iEnp2bS6W5Ym8CjoaOh1w&s",
    id: 38,
    rating: 4.7,
    delivery: 36,
    price: 120,
  },
  {
    name: "Atithi Shopee",
    img: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRGV2IRDGgR0eTLfxCiFLe51VDX1HFw6PUzrw&s",
    id: 44,
    rating: 4.7,
    delivery: 36,
    price: 120,
  },
  {
    name: "Lizzat Fruits",
    img: "https://i.ytimg.com/vi/Y1aVOCgVjhc/maxresdefault.jpg?sqp=-oaymwEmCIAKENAF8quKqQMa8AEB-AH-CYAC0AWKAgwIABABGHIgWygtMA8=&rs=AOn4CLASGk6xuSwubigEfcpa_OADeUM8rA",
    id: 46,
    rating: 4.4,
    delivery: 43,
    price: 80,
  },
];
